---
title: "Hela"
author: "MI YANG"
date: "`r doc_date()`"
vignette: >
  %\VignetteIndexEntry{Bioconductor style for HTML documents}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output: 
  BiocStyle::html_document

```{r include=FALSE, cache=FALSE}
library(clusterProfiler)
# https://www.bioconductor.org/packages/devel/bioc/vignettes/clusterProfiler/inst/doc/clusterProfiler.html#go-analysis

path <- "~/Documents/RWTH_Aachen"
source(paste(path,"/FUNCTIONS/general_functions.R", sep=""))
source(paste(path,"/HELA/HELA_functions.R", sep=""))
load("/Users/miyang/Documents/RWTH_Aachen/HELA/DATA/Hela_data.Rdata")

Hela_CCL2 <- c(2,6,7,12,13,14)
Hela_S3 <- c(5)
Hela_Kyoto <- c(1,4,8,9,10)
ALL <- c(1:10,12:14)
```


```{r include=FALSE, cache=FALSE}
x <- c("GPX3",  "GLRX",   "LBP",   "CRYAB", "DEFB1", "HCLS1",   "SOD2",   "HSPA2",
       "ORM1",  "IGFBP1", "PTHLH", "GPC3",  "IGFBP3","TOB1",    "MITF",   "NDRG1",
       "NR1H4", "FGFR3",  "PVR",   "IL6",   "PTPRM", "ERBB2",   "NID2",   "LAMB1",
       "COMP",  "PLS3",   "MCAM",  "SPP1",  "LAMC1", "COL4A2",  "COL4A1", "MYOC",
       "ANXA4", "TFPI2",  "CST6",  "SLPI",  "TIMP2", "CPM",     "GGT1",   "NNMT",
       "MAL",   "EEF1A2", "HGD",   "TCN2",  "CDA",   "PCCA",    "CRYM",   "PDXK",
       "STC1",  "WARS",  "HMOX1", "FXYD2", "RBP4",   "SLC6A12", "KDELR3", "ITM2B")
eg = bitr(x, fromType="SYMBOL", toType="ENTREZID", annoDb="org.Hs.eg.db")
head(eg)


library(org.Hs.eg.db)
keytypes(org.Hs.eg.db)
ids <- bitr(x, fromType="SYMBOL", toType=c("UNIPROT", "ENSEMBL"), annoDb="org.Hs.eg.db")
head(ids)

data(gcSample)
hg <- gcSample[[1]]
head(hg)


ego3 <- gseGO(geneList     = geneList,
              annoDb       = "org.Hs.eg.db",
              ont          = "CC",
              nPerm        = 1000,
              minGSSize    = 100,
              maxGSSize    = 500,
              pvalueCutoff = 0.05,
              verbose      = FALSE)












```











