---
title: "Hela project plots"
author: "MI YANG"
date: "`r doc_date()`"
vignette: >
  %\VignetteIndexEntry{Bioconductor style for HTML documents}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output: 
  BiocStyle::html_document
---
```{r include=FALSE, cache=FALSE}
library(RCircos)
library(openxlsx)
library(ggplot2) ; library(ggsignif)
path <- "~/Documents/RWTH_Aachen"
source(paste0(path,"/FUNCTIONS/general_functions.R"))
source(paste0(path,"/FUNCTIONS/PLOT.R"))
source(paste0(path,"/HELA/HELA_functions.R"))
load(paste0(path,"/HELA/DATA/Hela_data_log.Rdata"))
load(paste0(path,"/HELA/DATA/Hela_data_original.Rdata"))
load(paste0(path,"/HELA/DATA/Hela_data_AVG.Rdata"))
protein_names <- read.csv(paste0(path,"/HELA/DATA/protein_names"), row.names=1) ; protein_names <- protein_names$x

### define orders
Hela_CCL2 <- c(2,6,7,12,13,14)
Hela_Kyoto <- c(1,3,4,8,9,10)
Hela_total <- 1:14
```


# make the combinations
```{r include=FALSE, cache=FALSE}
library(openxlsx)
Proteome_all <- read.xlsx(paste0(path,"/HELA/ORIGINAL_DATA/Proteome_all161021_unlogged_ToMi.xlsx" ))
rownames(Proteome_all) <- Proteome_all[ ,1] ; Proteome_all <- Proteome_all[ ,-1]

original <- Proteome_all[ ,grep("O", colnames(Proteome_all))]
original <- original[ ,-which(colnames(original)=="Organism")]
original <- log10(original)
original <- data.matrix(original)
original[original<1] <- 1
original <- quantile_normalisation(original)

# We remove 4 cells: O_7_R1_final2 , O_7_R2  , O_13_R1 , O_13_R2_final2
original <- original[ ,-which(colnames(original) %in% c("O_7_R1_final2", "O_7_R2" , "O_13_R1" , "O_13_R2_final2"))]

################# top 1000 proteins
a <- rowMeans(original) ; names(a) <- rownames(original) ; a <- a[order(-a)]
original <- original[ rownames(original) %in% names(a)[1:1000] , ]
#################

## between replicates
combi_between_replicates <- c()
for(i in seq(1,length(colnames(original)),2) ) {
  pair <- c(colnames(original)[i],colnames(original)[i+1])
  combi_between_replicates <- rbind(combi_between_replicates, pair)
}

## between groups (CCL2 - Kyoto)
Hela_CCL2 <- c("O_2_R1","O_2_R2","O_7p7_R1","O_7p7_R2","O_13p7_R1","O_13p7_R2")
Hela_Kyoto <- c("O_1_R1","O_1_R2","O_3_R1","O_3_R2","O_4_R1","O_4_R2","O_9_R1","O_9_R2","O_10_R1","O_10_R2")
combi_between_groups <- expand.grid( Hela_CCL2, Hela_Kyoto)

## between cells of the same group
combi_between_cells_Hela_CCL2 <- t( combn(x=Hela_CCL2, m=2, FUN = NULL, simplify = TRUE ) ) 
combi_between_cells_Hela_Kyoto <- t( combn(x=Hela_Kyoto, m=2, FUN = NULL, simplify = TRUE ) ) 
combi_between_cells_of_same_group <- rbind(combi_between_cells_Hela_CCL2,combi_between_cells_Hela_Kyoto)

```



```{r include=FALSE, cache=FALSE}

corr_between_replicates <- c()
for(i in 1:length(combi_between_replicates[,1])) {
  corr <- cor.test(original[ ,as.character(combi_between_replicates[i,1])],original[ ,as.character(combi_between_replicates[i,2])])
  corr_between_replicates <- c(corr_between_replicates, corr$estimate )
}
names(corr_between_replicates) <- paste0(combi_between_replicates[ ,1],"_with_",combi_between_replicates[,2] )

corr_between_cells <- c()
for(i in 1:length(combi_between_cells_of_same_group[,1])) {
  corr <- cor.test(original[ ,as.character(combi_between_cells_of_same_group[i,1])],original[ ,as.character(combi_between_cells_of_same_group[i,2])])
  corr_between_cells <- c(corr_between_cells, corr$estimate )
}
names(corr_between_cells) <- paste0(combi_between_cells_of_same_group[ ,1],"_with_",combi_between_cells_of_same_group[,2] )

corr_between_groups <- c()
for(i in 1:length(combi_between_groups[,1])) {
  corr <- cor.test(original[ , as.character(combi_between_groups[i,1]) ], original[ , as.character(combi_between_groups[i,2]) ])
  corr_between_groups <- c(corr_between_groups, corr$estimate )
}
names(corr_between_groups) <- paste0(combi_between_groups[ ,1],"_with_",combi_between_groups[,2] )

wilcox.test(corr_between_replicates, corr_between_cells )

L <- list(corr_between_replicates, corr_between_cells, corr_between_groups) ; names(L) <- c("Between replicates", "Between cells of same group", "Between CCL2/Kyoto")

kruskal.test(L)

pdf(file=paste0(path,"/HELA/PLOT/combinatorial_correlation/correlation_boxplot.pdf"), height=10, width=14, compress=TRUE)
nice_boxplot_list(L, title="Combinatorial correlation")
dev.off()

pdf(file=paste0(path,"/HELA/PLOT/combinatorial_correlation/correlation_boxplot_Top1000_proteins.pdf"), height=10, width=14, compress=TRUE)
nice_boxplot_list(L, title="Combinatorial correlation")
dev.off()


```


```{r include=FALSE, cache=FALSE}
  result <- L
  result_transformed <- c()
  for (i in 1:length(result)) {
    v <- na.omit(result[[i]]) ; v <- cbind(rep(i,each=length(na.omit(result[[i]]))), v)
    result_transformed <- rbind(result_transformed, v)
    colnames(result_transformed) <- c("groups", "correlation")
  }
  result_transformed <- cbind(rownames(result_transformed), result_transformed)
  colnames(result_transformed)[1] <- "cell_pairs"
  result_transformed <- as.data.frame(result_transformed)
  result_transformed[,2] <- as.character(result_transformed[,2])
  result_transformed[result_transformed$groups==1,2] <- "Between replicates"
  result_transformed[result_transformed$groups==2,2] <- "Between cells of same group"
  result_transformed[result_transformed$groups==3,2] <- "Between CCL2/Kyoto"
  
  write.xlsx(result_transformed, paste0(path,"/HELA/PLOT/combinatorial_correlation/combinatorial_pearson_correlation_TABLE.xlsx"))
   
```


